spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:mariadb://localhost:3306/book_rental?serverTimezone=UTC
    url: jdbc:log4jdbc:mysql://localhost:3306/book_rental?serverTimezone=UTC
    username: cereal
    password: cereal

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jwt:
    salt: MYSALT
    Expmin: 30
