spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/book_rental?serverTimezone=UTC
    username: cereal
    password: cereal

server:
  port: 8082